from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


class GodotCapabilityError(RuntimeError):
    """Raised when the local Godot capability cannot complete safely."""


@dataclass(frozen=True)
class CommandResult:
    command: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str


class GodotAdapter:
    """Zero-dollar local adapter for deterministic Godot project operations.

    This adapter never downloads Godot, never reaches a paid service, and never
    shells through a remote provider. The executable must already be available
    locally or supplied explicitly.
    """

    def __init__(self, executable: str | None = None) -> None:
        self.executable = executable or self._discover_executable()

    @staticmethod
    def _discover_executable() -> str:
        for candidate in ("godot", "godot4", "Godot_v4"):
            resolved = shutil.which(candidate)
            if resolved:
                return resolved
        raise GodotCapabilityError(
            "Godot executable not found. Install Godot locally or pass executable=."
        )

    def _run(self, args: Sequence[str], cwd: Path | None = None) -> CommandResult:
        command = (self.executable, *args)
        process = subprocess.run(
            command,
            cwd=str(cwd) if cwd else None,
            capture_output=True,
            text=True,
            check=False,
        )
        result = CommandResult(command, process.returncode, process.stdout, process.stderr)
        if result.returncode != 0:
            raise GodotCapabilityError(
                f"Godot command failed ({result.returncode}): {' '.join(command)}\n{result.stderr.strip()}"
            )
        return result

    def health(self) -> CommandResult:
        return self._run(("--version",))

    def create_project(self, project_dir: str | Path, project_name: str) -> Path:
        root = Path(project_dir)
        root.mkdir(parents=True, exist_ok=True)
        project_file = root / "project.godot"
        if not project_file.exists():
            project_file.write_text(
                "\n".join(
                    [
                        "; Generated by Zero-Dollar Agent Fabric GodotAdapter",
                        "config_version=5",
                        "",
                        "[application]",
                        f'config/name="{project_name}"',
                        'run/main_scene="res://main.tscn"',
                        "",
                        "[display]",
                        "window/size/viewport_width=1280",
                        "window/size/viewport_height=720",
                        "",
                        "[rendering]",
                        'renderer/rendering_method="gl_compatibility"',
                        'renderer/rendering_method.mobile="gl_compatibility"',
                        "",
                    ]
                ),
                encoding="utf-8",
            )
        return project_file

    def generate_scene(self, project_dir: str | Path, scene_text: str, name: str = "main.tscn") -> Path:
        path = Path(project_dir) / name
        path.write_text(scene_text, encoding="utf-8")
        return path

    def import_assets(self, project_dir: str | Path, assets: Iterable[str | Path]) -> list[Path]:
        destination = Path(project_dir) / "assets"
        destination.mkdir(parents=True, exist_ok=True)
        copied: list[Path] = []
        for source_value in assets:
            source = Path(source_value)
            if not source.is_file():
                raise GodotCapabilityError(f"Asset does not exist: {source}")
            target = destination / source.name
            shutil.copy2(source, target)
            copied.append(target)
        return copied

    def attach_scripts(self, project_dir: str | Path, scripts: dict[str, str]) -> list[Path]:
        root = Path(project_dir) / "scripts"
        root.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []
        for relative_name, source in scripts.items():
            target = root / relative_name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(source, encoding="utf-8")
            written.append(target)
        return written

    def test_project(self, project_dir: str | Path) -> CommandResult:
        return self._run(("--headless", "--path", str(Path(project_dir)), "--editor", "--quit"))

    def render_preview(self, project_dir: str | Path, output: str | Path) -> CommandResult:
        output_path = Path(output)
        return self._run(
            (
                "--headless",
                "--path",
                str(Path(project_dir)),
                "--write-movie",
                str(output_path),
                "--quit-after",
                "1",
            )
        )

    def export_web(self, project_dir: str | Path, output: str | Path, preset: str = "Web") -> CommandResult:
        return self._run(
            ("--headless", "--path", str(Path(project_dir)), "--export-release", preset, str(Path(output)))
        )

    def export_desktop(
        self,
        project_dir: str | Path,
        output: str | Path,
        preset: str,
    ) -> CommandResult:
        return self._run(
            ("--headless", "--path", str(Path(project_dir)), "--export-release", preset, str(Path(output)))
        )

    def package_artifact(self, project_dir: str | Path, output_base: str | Path) -> Path:
        archive = shutil.make_archive(str(Path(output_base)), "zip", root_dir=str(Path(project_dir)))
        return Path(archive)

    def write_manifest(self, project_dir: str | Path, metadata: dict[str, object]) -> Path:
        path = Path(project_dir) / "capability-output.json"
        path.write_text(json.dumps(metadata, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        return path
